FROM node:8.6

WORKDIR /app

RUN apt-get update && \
    apt-get install -yq graphicsmagick && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /app && \
    npm install pm2 -g

RUN npm install && npm rebuild && npm run migrate

CMD [ "pm2-runtime", "start", "--env", "development", "processes-debug.json" ]