version: '3'

services:
  db:
    build: pg_db/.
    container_name: sim_db
    ports:
      - 5432:5432
    volumes:
      - ~/projects/simtrack_db:/var/lib/postgresql/data
      - ./pg_db:/pg
    expose:
      - "5432"

  app:
    build: .
    container_name: sim_back
    environment:
      DATABASE_HOST: db
    command: ["/app/wait-for.sh", "15", "pm2-docker", "start", "--auto-exit", "--env", "development", "processes.json"]
    volumes:
      - .:/app
    ports:
      - 8000:8080
    expose:
      - "8080"
    depends_on:
      - db
    links:
      - db

  web:
    build: ./../sim-track
    container_name: sim_front
    environment:
      API_ROOT: app
      API_PORT: 8080
    command: ["npm", "start"]
    volumes:
      - ./../sim-track:/app
    ports:
      - 8080:8080
    links:
      - app
