version: '3'

services:
  app:
    # build: .
    # image: back:t2
    build: .
    command:
      - node
      - "--inspect"
      - "bin/www"
    volumes:
      - .:/app
    ports:
      - 8000:8080
      - 9229:9229
      - 4433:4433
    env_file:
      - .docker-compose-dev.env
    entrypoint: |
      bash -c './app_boot.sh'

  rabbitmq:
    image: rabbitmq:3.11.4
    container_name: 'rabbitmq'
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASSWORD: "guest"
    ports:
      - 5672:5672

