FROM node:8.6

WORKDIR /app

COPY . /app

RUN apt-get update && \
    apt-get install -yq graphicsmagick && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /app && \
    npm install pm2 -g

#RUN npm install #&& 
#RUN npm rebuild #&&
#RUN npm run migrate #&&
#RUN pm2-runtime start --env development processes-debug.json

#CMD [ "npm", "run", "migrate" ]
#CMD [ "pm2-runtime", "start", "--env", "development", "processes-debug.json" ]
#CMD [ "npm", "start" ]