version: '3'

services:
  db:
    image: simtrackdb:latest
    container_name: sim_db
    ports:
      - 5432:5432
    volumes:
      - ~/projects/simtrack_db:/var/lib/postgresql/data
      - ./pg_db:/pg
    expose:
    expose:
      - "5432"

  app:
    image: simtrackback:latest
    container_name: sim_back
    environment:
      DATABASE_HOST: db
    command: ["/app/wait-for.sh", "5", "npm", "start"]
    volumes:
      - .:/app
    ports:
      - 8000:8080
    expose:
      - "8080"
    depends_on:
      - db
    links:
      - db

  web:
    image: simtrackfront:latest
    container_name: sim_front
    environment:
      API_ROOT: app
      API_PORT: 8080
    command: ["npm", "start"]
    volumes:
      - ./../sim-track-front:/app
    ports:
      - 8080:8080
    links:
      - app