version: '3'

services:
  db:
    image: postgres:9.6-alpine
    volumes:
      - ./../simtrack_db:/var/lib/postgresql/data
      - ./pg_db/dumps:/docker-entrypoint-initdb.d
      - ./pg_db:/pg
    ports:
      - 5432:5432
    env_file:
      - .docker-compose-dev.env
    restart: unless-stopped

  app:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8080
      - 9230:9230
    depends_on:
      - db
    env_file:
      - .docker-compose-dev.env
    entrypoint: |
      bash -c 'bash -s <<EOF
      npm install
      npm rebuild
      pm2-runtime start --env development processes-debug.json
      EOF'

  web:
    build: ./../sim-track
    volumes:
      - ./../sim-track:/app
    ports:
      - 8080:8080
    env_file:
      - .docker-compose-dev.env
    entrypoint: |
      bash -c 'bash -s <<EOF
      npm install
      npm rebuild
      npm start
      EOF'
