exports.TIMESHEET_REPORT_STATUS_SEND_FOR_CONFIRMATION = 5;

exports.TIMESHEET_USER_TYPE_FILTER = {
    EXTERNAL_USER: 'EXTERNAL_USER',
    NOT_EXTERNAL_USER: 'NOT_EXTERNAL_USER'
}

exports.USER_GLOBAL_ROLES = {
    EXTERNAL_USER: 'EXTERNAL_USER'
}