CREATE TABLE IF NOT EXISTS "metrics" ("id"   SERIAL , "type_id" INTEGER, "value" VARCHAR(255), "created_at" TIMESTAMP WITH TIME ZONE, "project_id" INTEGER REFERENCES "projects" ("id") ON DELETE NO ACTION ON UPDATE CASCADE, "sprint_id" INTEGER REFERENCES "sprints" ("id") ON DELETE NO ACTION ON UPDATE CASCADE, "user_id" INTEGER REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE CASCADE, PRIMARY KEY ("id"));
CREATE TABLE IF NOT EXISTS "metric_types" ("id" INTEGER NOT NULL , "name" VARCHAR(255) NOT NULL, PRIMARY KEY ("id"));
INSERT INTO metric_types VALUES (1, 'Дата начала проекта');
INSERT INTO metric_types VALUES (2, 'Дата завершения проекта');
INSERT INTO metric_types VALUES (3, 'Бюджет проекта без РР (часы)');
INSERT INTO metric_types VALUES (4, 'Бюджет проекта с РР (часы)');
INSERT INTO metric_types VALUES (5, 'Burndown по проекту без РР');
INSERT INTO metric_types VALUES (6, 'Burndown по проекту с РР');
INSERT INTO metric_types VALUES (7, 'Количество открытых багов');
INSERT INTO metric_types VALUES (8, 'Количество открытых багов от Заказчика');
INSERT INTO metric_types VALUES (9, 'Количество открытых регрессионных багов');
INSERT INTO metric_types VALUES (10, '% часов затраченных на роль 1(Account)');
INSERT INTO metric_types VALUES (11, '% часов затраченных на роль 2(PM)');
INSERT INTO metric_types VALUES (12, '% часов затраченных на роль 3(UX)');
INSERT INTO metric_types VALUES (13, '% часов затраченных на роль 4(Аналитик)');
INSERT INTO metric_types VALUES (14, '% часов затраченных на роль 5(Back)');
INSERT INTO metric_types VALUES (15, '% часов затраченных на роль 6(Front)');
INSERT INTO metric_types VALUES (16, '% часов затраченных на роль 7(Mobile)');
INSERT INTO metric_types VALUES (17, '% часов затраченных на роль 8(TeamLead(Code review))');
INSERT INTO metric_types VALUES (18, '% часов затраченных на роль 9(QA)');
INSERT INTO metric_types VALUES (19, '% часов затраченных на роль 10(Unbillable)');
INSERT INTO metric_types VALUES (20, 'Часы затраченные на роль 1(Account)');
INSERT INTO metric_types VALUES (21, 'Часы затраченные на роль 2(PM)');
INSERT INTO metric_types VALUES (22, 'Часы затраченные на роль 3(UX)');
INSERT INTO metric_types VALUES (23, 'Часы затраченные на роль 4(Аналитик)');
INSERT INTO metric_types VALUES (24, 'Часы затраченные на роль 5(Back)');
INSERT INTO metric_types VALUES (25, 'Часы затраченные на роль 6(Front)');
INSERT INTO metric_types VALUES (26, 'Часы затраченные на роль 7(Mobile)');
INSERT INTO metric_types VALUES (27, 'Часы затраченные на роль 8(TeamLead(Code review))');
INSERT INTO metric_types VALUES (28, 'Часы затраченные на роль 9(QA)');
INSERT INTO metric_types VALUES (29, 'Часы затраченные на роль 10(Unbillable)');
INSERT INTO metric_types VALUES (30, 'Burndown по спринтам без РР');
INSERT INTO metric_types VALUES (31, 'Burndown по спринтам с РР');
INSERT INTO metric_types VALUES (32, 'Динамика закрытия фич (с учетом трудозатрат)');
INSERT INTO metric_types VALUES (33, 'Трудозатрат на фичи без оценки');
INSERT INTO metric_types VALUES (34, 'Динамика списания времени на фичи');
INSERT INTO metric_types VALUES (35, 'Количество открытых задач типа 1(Фича)');
INSERT INTO metric_types VALUES (36, 'Количество открытых задач типа 2(Доп. Фича)');
INSERT INTO metric_types VALUES (37, 'Количество открытых задач типа 3(Баг)');
INSERT INTO metric_types VALUES (38, 'Количество открытых задач типа 4(Регрес. Баг)');
INSERT INTO metric_types VALUES (39, 'Количество открытых задач типа 5(Баг от клиента)');
INSERT INTO metric_types VALUES (40, 'Количество фич без оценки');