ALTER TABLE sprints ALTER COLUMN allotted_time SET DATA TYPE DECIMAL(10,2);
ALTER TABLE sprints ALTER COLUMN budget SET DATA TYPE DECIMAL(10,2);
ALTER TABLE sprints ALTER COLUMN risk_budget SET DATA TYPE DECIMAL(10,2);
ALTER TABLE sprints ADD COLUMN budget DECIMAL(10,2) DEFAULT NULL;
ALTER TABLE sprints ADD COLUMN risk_budget DECIMAL(10,2) DEFAULT NULL;